import { appConfig } from "./config.js";

const nowIso = "2026-07-21T09:00:00-06:00";

export const mockDb = {
  users: [
    {
      id: "user_demo_1",
      first_name: "Mariana",
      last_name: "Garcia",
      email: "familia.horizonte@example.com",
      phone: "7751234567",
      password_hash_placeholder: "hash_placeholder_no_productivo",
      email_verified: true,
      phone_verified: false,
      notification_email: true,
      notification_whatsapp: true,
      created_at: nowIso,
      updated_at: nowIso,
    },
  ],
  admins: [
    {
      id: "admin_demo_1",
      username: appConfig.access.adminUsername,
      role: "owner",
      name: "Alberto de la Fuente",
    },
  ],
  schools: [
    {
      id: "school_horizonte",
      name: "Colegio Horizonte",
      slug: "colegio-horizonte",
      access_code: "HORIZONTE",
      status: "active",
      logo: "assets/photoschool-logo-wordmark.png",
      cover_image: "assets/hero.png",
      contact_name: "Contacto autorizado",
      city: "Tulancingo",
      state: "Hidalgo",
      created_at: nowIso,
      updated_at: nowIso,
    },
    {
      id: "school_archive_inactive",
      name: "Colegio Archivo",
      slug: "colegio-archivo",
      access_code: "INACTIVA",
      status: "inactive",
      logo: "assets/photoschool-logo-wordmark.png",
      cover_image: "assets/hero.png",
      contact_name: "Contacto autorizado",
      city: "Pachuca",
      state: "Hidalgo",
      created_at: nowIso,
      updated_at: nowIso,
    },
  ],
  events: [
    {
      id: "event_hz_2026",
      school_id: "school_horizonte",
      schoolId: "school_horizonte",
      name: "Festival de Fin de Cursos 2026",
      schoolName: "Colegio Horizonte",
      slug: "festival-fin-cursos-2026",
      access_code: "FINCURSOS26",
      accessCode: "FINCURSOS26",
      event_type: "end_of_year",
      event_date: "2026-07-18",
      date: "2026-07-18",
      publication_mode: "immediate",
      publish_at: "2026-07-18T08:00:00-06:00",
      publishDate: "2026-07-18",
      expires_at: "2026-09-18T23:59:59-06:00",
      expiresAt: "2026-09-18",
      status: "active",
      public_visibility: false,
      gallery_id: "gallery_hz_2026",
      accessType: appConfig.access.type,
      coverTone: "cyan",
      categories: ["Ceremonia", "Individuales", "Familia", "Generacion", "Convivencia"],
      notes: "Evento privado con acceso por escuela y evento.",
      privateUrl: `${appConfig.brand.plannedDomain}/#/acceso`,
      estimatedStorageGb: 28,
      files_available: true,
      deletionAuditStatus: "programada_al_vencer",
      notification_settings: { email: true, whatsapp: true },
      created_at: nowIso,
      updated_at: nowIso,
    },
    {
      id: "event_spring_2026",
      school_id: "school_horizonte",
      schoolId: "school_horizonte",
      name: "Festival de Primavera",
      schoolName: "Colegio Horizonte",
      slug: "festival-primavera-2026",
      access_code: "PRIMAVERA26",
      accessCode: "PRIMAVERA26",
      event_type: "spring",
      event_date: "2026-08-12",
      date: "2026-08-12",
      publication_mode: "scheduled",
      publish_at: "2026-07-25T10:00:00-06:00",
      publishDate: "2026-07-25",
      expires_at: "2026-09-25T23:59:59-06:00",
      expiresAt: "2026-09-25",
      status: "scheduled",
      public_visibility: false,
      gallery_id: "gallery_spring_2026",
      accessType: appConfig.access.type,
      coverTone: "cyan",
      categories: ["Ceremonia", "Familia"],
      notes: "Evento programado para validar espera y contador.",
      privateUrl: `${appConfig.brand.plannedDomain}/#/acceso`,
      estimatedStorageGb: 18,
      files_available: true,
      deletionAuditStatus: "programada_al_vencer",
      notification_settings: { email: true, whatsapp: true },
      created_at: nowIso,
      updated_at: nowIso,
    },
    {
      id: "event_mothers_2026",
      school_id: "school_horizonte",
      schoolId: "school_horizonte",
      name: "Día de las Madres",
      schoolName: "Colegio Horizonte",
      slug: "dia-de-las-madres-2026",
      access_code: "MAMAS26",
      accessCode: "MAMAS26",
      event_type: "mothers_day",
      event_date: "2026-05-10",
      date: "2026-05-10",
      publication_mode: "immediate",
      publish_at: "2026-05-10T08:00:00-06:00",
      publishDate: "2026-05-10",
      expires_at: "2026-07-10T23:59:59-06:00",
      expiresAt: "2026-07-10",
      status: "expired",
      public_visibility: false,
      gallery_id: "gallery_mothers_2026",
      accessType: appConfig.access.type,
      coverTone: "charcoal",
      categories: ["Familia", "Convivencia"],
      notes: "Evento vencido para validar reactivación.",
      privateUrl: `${appConfig.brand.plannedDomain}/#/acceso`,
      estimatedStorageGb: 12,
      files_available: true,
      deletionAuditStatus: "pendiente",
      notification_settings: { email: true, whatsapp: true },
      created_at: nowIso,
      updated_at: nowIso,
    },
    {
      id: "event_deleted_2026",
      school_id: "school_horizonte",
      schoolId: "school_horizonte",
      name: "Evento Deportivo Eliminado",
      schoolName: "Colegio Horizonte",
      slug: "evento-deportivo-eliminado",
      access_code: "DEPORTE26",
      accessCode: "DEPORTE26",
      event_type: "sports",
      event_date: "2026-04-01",
      date: "2026-04-01",
      publication_mode: "immediate",
      publish_at: "2026-04-01T08:00:00-06:00",
      publishDate: "2026-04-01",
      expires_at: "2026-06-01T23:59:59-06:00",
      expiresAt: "2026-06-01",
      status: "deleted",
      public_visibility: false,
      gallery_id: "gallery_deleted_2026",
      accessType: appConfig.access.type,
      coverTone: "charcoal",
      categories: ["Eventos deportivos"],
      notes: "Evento eliminado; sus archivos ya no pueden reactivarse.",
      privateUrl: `${appConfig.brand.plannedDomain}/#/acceso`,
      estimatedStorageGb: 0,
      files_available: false,
      deletionAuditStatus: "archivos_eliminados",
      notification_settings: { email: false, whatsapp: false },
      created_at: nowIso,
      updated_at: nowIso,
    },
  ],
  galleries: [
    {
      id: "gallery_hz_2026",
      eventId: "event_hz_2026",
      event_id: "event_hz_2026",
      school_id: "school_horizonte",
      type: "private",
      title: "Festival de Fin de Cursos 2026",
      slug: "festival-fin-cursos-2026",
      status: "active",
      photoCount: 18,
      expiresAt: "2026-09-18",
      expires_at: "2026-09-18T23:59:59-06:00",
      publish_at: "2026-07-18T08:00:00-06:00",
      featured: false,
      files_available: true,
    },
    {
      id: "gallery_spring_2026",
      eventId: "event_spring_2026",
      event_id: "event_spring_2026",
      school_id: "school_horizonte",
      type: "private",
      title: "Festival de Primavera",
      slug: "festival-primavera-2026",
      status: "scheduled",
      photoCount: 0,
      expiresAt: "2026-09-25",
      expires_at: "2026-09-25T23:59:59-06:00",
      publish_at: "2026-07-25T10:00:00-06:00",
      featured: false,
      files_available: true,
    },
    {
      id: "gallery_mothers_2026",
      eventId: "event_mothers_2026",
      event_id: "event_mothers_2026",
      school_id: "school_horizonte",
      type: "private",
      title: "Día de las Madres",
      slug: "dia-de-las-madres-2026",
      status: "expired",
      photoCount: 6,
      expiresAt: "2026-07-10",
      expires_at: "2026-07-10T23:59:59-06:00",
      publish_at: "2026-05-10T08:00:00-06:00",
      featured: false,
      files_available: true,
    },
    {
      id: "gallery_deleted_2026",
      eventId: "event_deleted_2026",
      event_id: "event_deleted_2026",
      school_id: "school_horizonte",
      type: "private",
      title: "Evento Deportivo Eliminado",
      slug: "evento-deportivo-eliminado",
      status: "deleted",
      photoCount: 0,
      expiresAt: "2026-06-01",
      expires_at: "2026-06-01T23:59:59-06:00",
      publish_at: "2026-04-01T08:00:00-06:00",
      featured: false,
      files_available: false,
    },
  ],
  public_galleries: [
    {
      id: "public_graduaciones",
      title: "Graduaciones",
      slug: "graduaciones",
      category: "Graduaciones",
      description: "Cobertura editorial de ceremonias, entregas y retratos de generación.",
      status: "active",
      type: "public",
      featured: true,
      publish_at: "2026-07-01T08:00:00-06:00",
      cta: "WhatsApp",
      coverPhotoIndex: 2,
    },
    {
      id: "public_festivales",
      title: "Festivales escolares",
      slug: "festivales-escolares",
      category: "Festivales escolares",
      description: "Momentos representativos de eventos culturales y celebraciones escolares.",
      status: "active",
      type: "public",
      featured: true,
      publish_at: "2026-07-01T08:00:00-06:00",
      cta: "WhatsApp",
      coverPhotoIndex: 5,
    },
    {
      id: "public_credenciales",
      title: "Credencialización y anuarios",
      slug: "credencializacion-anuarios",
      category: "Credencialización",
      description: "Muestra visual de servicios complementarios para escuelas.",
      status: "scheduled",
      type: "public",
      featured: false,
      publish_at: "2026-08-01T08:00:00-06:00",
      cta: "WhatsApp",
      coverPhotoIndex: 7,
    },
  ],
  photos: [],
  photo_variants: [],
  access_codes: [
    {
      id: "access_school_horizonte",
      school_id: "school_horizonte",
      code: "HORIZONTE",
      type: "school",
      active: true,
    },
    {
      id: "access_hz_2026",
      eventId: "event_hz_2026",
      event_id: "event_hz_2026",
      school_id: "school_horizonte",
      code: "FINCURSOS26",
      type: "event",
      active: true,
    },
  ],
  user_gallery_access: [
    {
      id: "uga_demo_1",
      user_id: "user_demo_1",
      school_id: "school_horizonte",
      event_id: "event_hz_2026",
      granted_at: "2026-07-18T11:00:00-06:00",
      expires_at: "2026-09-18T23:59:59-06:00",
      access_source: "codigo",
      revoked_at: null,
    },
    {
      id: "uga_demo_2",
      user_id: "user_demo_1",
      school_id: "school_horizonte",
      event_id: "event_spring_2026",
      granted_at: "2026-07-21T09:00:00-06:00",
      expires_at: "2026-09-25T23:59:59-06:00",
      access_source: "notificacion",
      revoked_at: null,
    },
  ],
  notification_subscriptions: [
    {
      id: "sub_demo_1",
      user_id: "user_demo_1",
      event_id: "event_spring_2026",
      email_enabled: true,
      whatsapp_enabled: true,
      consent_at: nowIso,
    },
  ],
  notifications: [
    {
      id: "notif_demo_1",
      user_id: "user_demo_1",
      event_id: "event_hz_2026",
      channel: "email",
      type: "gallery_published",
      status: "simulated",
      sent_at: "2026-07-18T08:10:00-06:00",
      read_at: null,
      template: "Tu galería de Festival de Fin de Cursos 2026 ya está disponible",
      attempts: 1,
      reason: "publicación",
      error: "",
    },
    {
      id: "notif_demo_2",
      user_id: "user_demo_1",
      event_id: "event_hz_2026",
      channel: "whatsapp",
      type: "order_confirmed",
      status: "simulated",
      sent_at: "2026-07-18T10:44:00-06:00",
      read_at: null,
      template: "Tu pedido en PhotoSchool fue confirmado.",
      attempts: 1,
      reason: "pedido",
      error: "",
    },
  ],
  customers: [
    { id: "customer_demo_1", name: "Mariana Garcia", email: "mariana.horizonte@example.com" },
  ],
  carts: [],
  cart_items: [],
  orders: [
    {
      id: "order_demo_1",
      orderNumber: "PS-20260718-1042",
      customerName: "Mariana Garcia",
      customerEmail: "familia.horizonte@example.com",
      eventId: "event_hz_2026",
      eventName: "Festival de Fin de Cursos 2026",
      schoolName: "Colegio Horizonte",
      createdAt: "2026-07-18T10:42:00-06:00",
      photoCount: 6,
      deliveryType: "Recolección personal",
      total: 270,
      paymentMethod: "Mercado Pago",
      paymentStatus: "Aprobado",
      preparationStatus: "Listo para entregar",
      items: [
        { photoId: "HZ26-0001", productType: "Impresion 5x7", printCopies: 1 },
        { photoId: "HZ26-0002", productType: "Impresion 5x7", printCopies: 1 },
        { photoId: "HZ26-0003", productType: "Impresion 5x7", printCopies: 1 },
        { photoId: "HZ26-0004", productType: "Impresion 5x7", printCopies: 1 },
        { photoId: "HZ26-0005", productType: "Impresion 5x7", printCopies: 1 },
        { photoId: "HZ26-0006", productType: "Impresion 5x7", printCopies: 1 },
      ],
    },
  ],
  order_items: [],
  payments: [
    {
      id: "payment_demo_1",
      orderId: "order_demo_1",
      method: "mercado_pago",
      simulation: true,
      status: "approved",
    },
  ],
  downloads: [
    {
      id: "download_policy_demo",
      orderId: "order_demo_1",
      event_id: "event_hz_2026",
      user_id: "user_demo_1",
      available_at: "2026-07-18T10:44:00-06:00",
      expires_at: "2026-07-25T10:44:00-06:00",
      status: "available",
      availableDaysAfterPayment: appConfig.lifecycle.downloadAvailabilityDays,
      signedLinksRequiredInProduction: true,
    },
  ],
  print_jobs: [
    {
      id: "print_job_demo_1",
      orderId: "order_demo_1",
      event_id: "event_hz_2026",
      user_id: "user_demo_1",
      deliveryType: appConfig.delivery.printDeliveryType,
      status: "ready_for_pickup",
    },
  ],
  pricing_rules: appConfig.pricing.volumeRules,
  audit_logs: [
    {
      id: "audit_policy_1",
      event: "gallery_expiration_policy",
      detail:
        "Al vencer, las fotos se eliminaran o archivaran; pedidos y pagos se conservaran.",
    },
    {
      id: "audit_policy_2",
      event: "backend_required",
      detail:
        "En producción, permisos, cron, expiración, pagos y enlaces firmados se validarán en backend.",
    },
  ],
};

const categories = ["Ceremonia", "Individuales", "Familia", "Generacion", "Convivencia"];
const titles = [
  "Escenario principal",
  "Retrato escolar",
  "Foto familiar",
  "Grupo generacional",
  "Convivencia",
  "Entrega de diplomas",
  "Sonrisa individual",
  "Abrazo familiar",
  "Linea de generacion",
  "Patio escolar",
  "Aplausos",
  "Retrato formal",
  "Familia completa",
  "Generacion 2026",
  "Amistades",
  "Diploma",
  "Pose individual",
  "Cierre de evento",
];

mockDb.photos = Array.from({ length: 18 }, (_, index) => {
  const number = String(index + 1).padStart(4, "0");
  const category = categories[index % categories.length];
  return {
    id: `photo_hz26_${number}`,
    eventId: "event_hz_2026",
    event_id: "event_hz_2026",
    galleryId: "gallery_hz_2026",
    gallery_id: "gallery_hz_2026",
    identifier: `HZ26-${number}`,
    title: titles[index],
    category,
    published: true,
    watermarkStatus: "aplicada",
    variants: {
      thumbnail: "generated-demo-svg",
      protectedView: "generated-demo-svg",
      originalPrivate: "private-storage-future",
    },
    metadata: {
      sequence: index + 1,
      lowResolutionDemo: true,
    },
  };
});
